### PR TITLE
Initial commit/push of documentation added for the "-P', "-S", and "-O" command line options.

### PR DESCRIPTION
**Pull request by mosherubin**
SUBMIT DOCUMENTATION FOR FRIDA-TRACE OPTIONS -P, -S, -O

In January 2020 I submitted a pull request to add new functionality 
(-P, -S, -O) to frida-trace.  I finally got around to composing 
documentation for these features.  The following changes were made
to the frida-website repository:

- The base frida-trace documentation page (frida-trace.md) was 
  updated with documentation for these features.
- The latest frida-trace help listing was incorporated into the page.
- A new markdown page (session-initialization-primer.md) was written, 
  presenting a comprehensive example describing how to use the "-S" 
  feature.
- The "-S" documentation contains a link to the new page 
  "session-initialization-primer.md".

### CODE REVIEW

**Review by oleavr — CHANGES_REQUESTED** [review]
Wow, thanks so much, this is awesome! 😍

The only last-minute tweaks I can think of is to make sure that the JavaScript example code follows the most common conventions:
- camelCase for variable and function names (PascalCase for class names)
- Opening curly brace on the same line as the construct that opens it, and opening/closing on the same line for `else` / `else if`, e.g.: `} else {`
- Use modern syntax now that QuickJS has replaced Duktape and we support ES2020 syntax in both runtimes without a compilation step. This means e.g. `onEnter: function (log, args, state) {` becomes `onEnter(log, args, state) {`, to never use `var` but always use `const` or `let` instead, etc. More details on the style we're using can be found [here](https://github.com/frida/frida/blob/master/CONTRIBUTING.md#rules-for-javascript).

**Comment by mosherubin** [comment]
Oleavr,

You should know that I carried the weight of providing documentation for features I helped implement for many months.  I recently decided that it was downright unfair to provide a tantalizing feature such as "--initialize-session"/"-S" without explaining how to use it.  I believe I will begin sleeping better at night now that it's done. <g>

I modified the documentation's embedded JavaScript code as per your comments.  The only change I was unable to make was removing the "function" keyword from the core.js and ms-windows.js shared code libraries.  When I removed the keyword, I received the following error:

```
@>frida-trace -p 6980 --decorate -i "gdi32full.dll!ExtTextOutW" -S ms-windows.js -S core.js
Failed to start tracing: Error: Unable to load ms-windows.js: SyntaxError: Illegal return statement
    at eval (<anonymous>)
    at Agent.init (agent.ts:22:26)
    at frida/runtime/message-dispatcher.js:13:1
    at c (frida/runtime/message-dispatcher.js:23:1)
    at Agent.init (agent.ts:24:23)
    at frida/runtime/message-dispatcher.js:13:1
    at c (frida/runtime/message-dispatcher.js:23:1)
```
Other than that, I hope it meets your editorial standards!

**Comment by mosherubin** [comment]
Hi oleavr,

I see the pull requested has not been merged.  Is there still something I need to do?

Happy New Year,

Moshe

**Comment by oleavr** [comment]
@mosherubin So sorry it took me ages to pick this back up, I got sick and accumulated a lot of backlog that I'm still working my way through.

This is really amazing work! 😍 Given that it's taken me so long to get back to this, I took the liberty of applying the second round of review feedback myself. I didn't get a chance to test the final version on Windows, but I did test the `ms-windows.js` bits one by one. Appreciate it if you could open a PR in case you see something off – or something you'd prefer done differently. The main changes I've done are:

- Using Markdown syntax as much as possible, avoiding HTML where possible.
- Breaking lines at 80 cols.
- Using JSDoc syntax for documenting functions.
- Name the functions so they can be called directly, without assigning them to `state`.
- Modernize the JavaScript further (template literals, `for of`, destructuring syntax, Map data structure, , etc.).

Happy New Year! 🎉

**Comment by mosherubin** [comment]
Hello Ole,

I know you and the Frida project well enough to know that, if I didn't hear
from you about the PR, you were busy up to your neck in backlogs! My
sincerest thanks for accepting my submission, and an especially grateful
thumbs-up for the substantial cleanup. Your doing it saved many
back-and-forths. I am absolutely convinced it is now a pearl!

As I wrote when I submitted it, I had a great feeling of having let the
project down by not submitting documentation - in effect, the feature was
cryptic and not usable by others. I can rest now knowing I have done my
contributory duty.

Thank you for the privilege of contributing to Frida  I don't think you've
heard the last from me (and that's a threat 😉)!

Best regards, and stay well,

Moshe

**Comment by oleavr** [comment]
@mosherubin Awesome! Glad to hear that, looking forward to it! 😊

Take care and stay safe,
Ole André

**Pull request merged**
