### PR TITLE
Translation into other languages

### PR DESCRIPTION
**Pull request by 4masaka**
related to #156 

I made the following changes to use jekyll-multiple-languages-plugin

1. Add `i18n` directory
2. Add language files to `i18n`
3. Add language setting to `_config.yml`

and other changes
1. Translate the preface of `index.md` into Japanese
2. Change `gems` to `plugins` in `_config.yml`

### CODE REVIEW

**Comment by oleavr** [comment]
Awesome! 🚀 (Apologies for the delay here, was not intentional.)

Unless you plan on translating the whole website in one go, it would be good to make the untranslated parts load the English resource until translated.

**Comment by 4masaka** [comment]
I deleted Untranslated parts!
I apologize for the delay 😔

**Comment by XieEDeHeiShou** [comment]
Hoping this pr could be merged soon, I've prepared to create another pr for the javascript api's chinese translation.

**Comment by XieEDeHeiShou** [comment]
Is there any plan to finish this pr this weekend? @4masaka

**Comment by 4masaka** [comment]
Removed duplicate pdf files and fixed broken news section!(and occured conflict...sorry)

by the way, `jekyll-multiple-languages-plugin` says
```
There are no global posts. The posts are localized by language. And your posts will live in the _i18n/[lang]/_posts directory. So if, for example, you have English language on your website you should put your posts on _i18n/en/_posts directory.
```
I don't plan to translate the news section, but it seems I need to put _posts in other languages directories

**Comment by oleavr** [comment]
Thanks a lot! Merged :tada:

There's not yet any links to the Japanese version, but let's do that as a separate PR if you're interested. :raised_hands:

**Comment by XieEDeHeiShou** [comment]
🎉

**Comment by oleavr** [comment]
(We also need to figure out how to fix the Japanese News section.)

**Pull request merged**
